# Generated by Django 3.1.4 on 2020-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=144)),
                ('phoneNum', models.CharField(blank=True, max_length=144)),
                ('name', models.CharField(blank=True, max_length=144)),
            ],
        ),
    ]
