# Generated by Django 3.1.4 on 2020-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='categoryText',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AddField(
            model_name='post',
            name='nameText',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AddField(
            model_name='post',
            name='phoneNumText',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
