# Generated by Django 3.1.4 on 2020-12-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryText',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nameText',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='phoneNumText',
            new_name='phoneNum',
        ),
    ]
